[package]
name = "makepad-7guis-temp-conv"
version = "0.3.0"
edition = "2021"
description = "Makepad counter example"
license = "MIT OR Apache-2.0"

[dependencies]
makepad-widgets = { path = "../../makepad/widgets", version = "0.6.0" }
